### ISSUE TITLE
not able to build on Google Colab

### ISSUE THREAD

**Issue by mscratnesh** [aeron7/nsepython#8]
while try to build the script with NSEPython getting error as  Build failed: arm-linux-androideabi-gfortran not found.

**Comment by aeron7** [comment]
Check https://unofficed.com/nse-python/documentation/ 

Google Cloud, AWS, Servers
This current version of scrapper does not work with AWS, Google Cloud and web servers. It is not a problem of Python Request. Nse’s robots.txt has blocked all webservers all together. See here [NSE Robots Txt](https://www.nseindia.com/robots.txt)

You can use the curl method and initiate shell commands using Python if you want to do it.

I do not plan to add Curl Method in the library unless I see some other library doing it because – That will increase the load in NSE servers and they will guard up their firewalls causing lots of problems for general scavengers like us like they did with their old website.
